# site settings
title: Leif Hill
subtitle: Software Engineer
email: leifhill.business@gmail.com
description:
baseurl: "/home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/leif-hill
  LinkedIn: https://www.linkedin.com/in/leif-hill/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
